import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

// import { Archivo } from "next/font/google";
// const archivo = Archivo({
//   variable: "--font-archivo",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// });

export const metadata = {
  title: {
    default: "Create Next App",
    template: "%s -ITI2025.com",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Hand:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      {/* if you need to use archivo font uncomment the line above and comment the
      link of the another font in the head and you should write this class in
      body tag className={archivo.className} */}
      <body>
        <Navbar />
        {children}
        <Footer />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-QF8IbJZjZrMoEBc4iVdcfXrRrX9K7hrk1iRklVm9Bq0pEmSm0zZLVf9x5+fFnxZh"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
